### ISSUE TITLE
Add support for custom cwd

### ISSUE THREAD

**Issue by dferber90** [blaugold/webpack-node-server-plugin#1]
First of all thanks for this great package! I tried several different ones and this was the easiest to get started with and I really like that it requires no configuration.

### Feature Request
Allow to set a custom [`cwd`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) for the spawned node process.

It would be useful if this plugin accepted a new `cwd` option which it then uses when spawning the child process.

```
new WebpackNodeServerPlugin({
    cwd?: String;
})
```

### Situation
I'm using this plugin to start a web server after the build completed. The compiled file goes into a `dist-development` subfolder of where the webpack node process was started from. The web server then tries to serve files statically. These files are emitted to the same `dist-development` folder.

In production, the server gets started from the folder it is in, so it can locate the files. During development the server gets started from the parent folder, because that's where webpack was started from, and the spawned process inherits the cwd.

I manually edited this plugin in my `node_modules`, and was able to make everything work by adding `cwd: 'dist-development'` to the spawn options [here](https://github.com/blaugold/webpack-node-server-plugin/blob/master/src/node-server-plugin.ts#L151).

```diff
- var childProcess = _this.child_process.spawn('node', [path], { stdio: 'inherit' });
+ var childProcess = _this.child_process.spawn('node', [path], { stdio: 'inherit', cwd: 'dist-development' }); 
```

Would you accept a PR adding this functionality?

**Comment by blaugold** [comment]
Thanks, I'm glad you like it. I have added some options for how the script is spawned. The options for `spawn` are now configurable through the plugin config:
https://github.com/blaugold/webpack-node-server-plugin/blob/99f605da404d1d4eb25ecc88365dfa0a24832ebc/src/config.ts#L41

In your webpack config this should do what you want:
`new NodeServerPlugin({ spawnOptions: { cwd: 'dist-development' } })`

Just be aware that there is a breaking change in this release (v1.0.0), where the plugin is now exported as the named export `NodeServerPlugin`. The package README show how to import the plugin from now on.

And thanks for the pr, but I think this should address your use case.

**Comment by dferber90** [comment]
I like that solution way more than my quick-n-dirty proposal.

🙏Just tired it out and it works like a charm. Thanks!
