### ISSUE TITLE
DeprecationWarning: Tapable.Plugin is Deprecated

### ISSUE THREAD

**Issue by medelman17** [blaugold/webpack-node-server-plugin#4]
It appears that this plugin needs to be updated to work with Webpack's new 'hooks' api. _See_ #https://github.com/webpack/webpack/issues/6568

> (node:7514) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
>     at NodeServerPlugin._NodeServerPlugin.apply (/Users/michaeljosephedelman/WebstormProjects/RambleRehash/node_modules/webpack-node-server-plugin/src/node-server-plugin.js:58:18)

**Comment by blaugold** [comment]
@medelman17 Thanks for the reminder. Is now fixed in `1.0.1`.
